[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"
HUGGINGFACEHUB_API_TOKEN = "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"

